# Generated by Django 4.2.3 on 2023-07-20 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('failed_login_attempts', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FailedLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('count', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PermanentBlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('is_permanently_blocked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BlockedIO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('io_type', models.CharField(max_length=50)),
                ('blocked_At', models.DateTimeField(auto_now_add=True)),
                ('duration_minutes', models.PositiveBigIntegerField(default=10)),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ip_block.blockedip')),
            ],
        ),
    ]
